apiVersion: v1
kind: Namespace
metadata:
  name: fairsplit-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairsplit
  namespace: fairsplit-system
spec:
  selector:
    matchLabels:
      app: fairsplit
  template:
    metadata:
      labels:
        app: fairsplit
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: fairsplit-api
        image: fairsplit-api-image