apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/fairsplit/
patchesStrategicMerge:
- ./dev-fairsplit-patch.yaml
images:
- name: fairsplit-api-image
  newName: fairsplit-api
  newTag: "1.0"