apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/fairsplit/
- ./dev-fairsplit-vault.yaml
patches:
- path: ./dev-fairsplit-patch-deploy.yaml
- path: ./dev-fairsplit-patch-service.yaml
- path: ./dev-fairsplit-vault-patch.yaml
images:
- name: fairsplit-api-image
  newName: fairsplit-api
  newTag: "1.0"
- name: service-image
  newName: fairsplit-api
  newTag: "1.0"
